-- local wk = require("which-key")
--
-- -- local mappings = {
-- --     ["<leader>h"] = {
-- --         name = "Harpoon",
-- --         a = { "harpoon.mark.add_file", "Harpoon: add mark"},
-- --         m = { ":lua harpoon.ui.toggle_quick_menu", "Harpoon: toggle mark menu"},
-- --         -- 1 = {"harpoon.ui.nav_file(1)", "Harpoon: Go to Mark 1"},
-- --         -- 2 = {"harpoon.ui.nav_file(2)", "Harpoon: Go to Mark 2"},
-- --         -- 3 = {"harpoon.ui.nav_file(3)", "Harpoon: Go to Mark 3"},
-- --         -- 4 = {"harpoon.ui.nav_file(4)", "Harpoon: Go to Mark 4"},
-- --     },
-- --     ["<leader>t"] = {":Neotree toggle<cr>", "NeoTree Open"},
-- -- }
--
-- wk.register(mappings,opts)
